version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for frontend deployment..."

  pre_build:
    commands:
      - echo "=== FRONTEND DEPLOYMENT TO AMPLIFY ==="
      - echo "Extracting backend configuration from existing stack..."
      - export API_GATEWAY_URL=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export IDENTITY_POOL_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomain`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export AWS_REGION=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`Region`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export FRONTEND_URL="https://main.${AMPLIFY_APP_ID}.amplifyapp.com"
      - echo "Configuration extracted:"
      - echo "API Gateway URL: $API_GATEWAY_URL"
      - echo "User Pool ID: $USER_POOL_ID"
      - echo "Region: $AWS_REGION"
      - echo "Frontend URL: $FRONTEND_URL"

  build:
    commands:
      - echo "Building Next.js frontend..."
      - cd frontend
      - echo "Installing frontend dependencies..."
      - npm ci
      - echo "Setting environment variables for build..."
      - echo "NEXT_PUBLIC_API_BASE_URL=$API_GATEWAY_URL" > .env.local
      - echo "NEXT_PUBLIC_AWS_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=$USER_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_DOMAIN=$COGNITO_DOMAIN" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN=$FRONTEND_URL/auth/callback" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT=$FRONTEND_URL" >> .env.local
      - echo "Environment file created:"
      - cat .env.local
      - echo "Building Next.js application..."
      - npm run build
      - echo "Creating deployment package..."
      - cd out
      - zip -r ../build.zip .
      - cd ..
      - echo "Build package created: $(ls -la build.zip)"

  post_build:
    commands:
      - echo "Deploying to Amplify..."
      - |
        # Create Amplify deployment
        echo "Creating Amplify deployment..."
        DEPLOYMENT_RESULT=$(aws amplify create-deployment --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION --output json)
        
        if echo "$DEPLOYMENT_RESULT" | grep -q "zipUploadUrl"; then
          echo "SUCCESS: Deployment created"
          UPLOAD_URL=$(echo "$DEPLOYMENT_RESULT" | jq -r '.zipUploadUrl')
          JOB_ID=$(echo "$DEPLOYMENT_RESULT" | jq -r '.jobId')
          echo "Upload URL obtained, Job ID: $JOB_ID"
        else
          echo "ERROR: Failed to create deployment"
          echo "$DEPLOYMENT_RESULT"
          exit 1
        fi
      - |
        # Upload build package
        echo "Uploading build package to Amplify..."
        UPLOAD_RESULT=$(curl -X PUT -T build.zip "$UPLOAD_URL" -w "%{http_code}" -o /tmp/upload_response.txt -s)
        
        if [ "$UPLOAD_RESULT" = "200" ]; then
          echo "SUCCESS: Build package uploaded successfully"
        else
          echo "ERROR: Upload failed with HTTP code: $UPLOAD_RESULT"
          echo "Response: $(cat /tmp/upload_response.txt)"
          exit 1
        fi
      - |
        # Start deployment
        echo "Starting Amplify deployment..."
        aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION
        
        if [ $? -eq 0 ]; then
          echo "SUCCESS: Amplify deployment started"
          echo "Monitor progress at: https://console.aws.amazon.com/amplify/home?region=$AWS_DEFAULT_REGION#/$AMPLIFY_APP_ID"
          echo "Frontend will be available at: https://main.$AMPLIFY_APP_ID.amplifyapp.com"
        else
          echo "ERROR: Failed to start deployment"
          exit 1
        fi
      - echo "=== DEPLOYMENT COMPLETE ==="
      - echo "Frontend deployed to Amplify successfully!"
      - echo "URL: https://main.$AMPLIFY_APP_ID.amplifyapp.com"