version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Installing zip and jq utilities for frontend..."
      - yum install -y zip jq

  pre_build:
    commands:
      - echo "=== BACKEND DEPLOYMENT ==="
      - echo "Changing into backend directory"
      - cd backend
      - echo "Installing backend dependencies..."
      - npm ci
      - echo "Installing Lambda function dependencies..."
      - |
        # Install dependencies for all Lambda functions
        for lambda_dir in lambda/*/; do
          if [ -f "${lambda_dir}package.json" ]; then
            echo "Installing dependencies for $(basename $lambda_dir)..."
            (cd "$lambda_dir" && npm ci --production --silent) || echo "Warning: Failed to install dependencies for $lambda_dir"
          fi
        done
      - echo "Building TypeScript..."
      - npm run build
      - echo "Bootstrapping CDK (if not already bootstrapped)..."
      - |
        # Set region from CodeBuild environment (AWS_DEFAULT_REGION is provided by CodeBuild)
        export AWS_REGION=${AWS_DEFAULT_REGION:-$CDK_DEFAULT_REGION}
        echo "Using AWS Region: $AWS_REGION"
        # Check if already bootstrapped to avoid errors
        if aws cloudformation describe-stacks --stack-name CDKToolkit --region $AWS_REGION >/dev/null 2>&1; then
          echo "CDK already bootstrapped, skipping..."
        else
          echo "Bootstrapping CDK for the first time..."
          cdk bootstrap --require-approval never --context amplifyAppId=$AMPLIFY_APP_ID
        fi

  build:
    commands:
      - echo "Deploying CDK stack..."
      - cdk deploy --require-approval never --context amplifyAppId=$AMPLIFY_APP_ID
      - |
        if [ $? -ne 0 ]; then
          echo "CDK deployment failed. Skipping frontend deployment."
          exit 1
        fi
      - echo "CDK deployment complete."
      - echo "Extracting API Gateway URL and Cognito configuration..."
      - cd ..
      - export STACK_NAME=${STACK_NAME:-AdaClaraUnifiedStack}
      - export AWS_REGION=${AWS_DEFAULT_REGION:-$CDK_DEFAULT_REGION}
      - export API_GATEWAY_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' --output text --region $AWS_REGION)
      - |
        # Ensure trailing slash for Next.js static export compatibility
        if [[ ! "$API_GATEWAY_URL" =~ /$ ]]; then
          export API_GATEWAY_URL="${API_GATEWAY_URL}/"
        fi
      - export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text --region $AWS_REGION)
      - export USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text --region $AWS_REGION)
      - export IDENTITY_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' --output text --region $AWS_REGION)
      - export COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomain`].OutputValue' --output text --region $AWS_REGION)
      # AMPLIFY_APP_ID is passed from deploy.sh as environment variable (created before CDK deployment)
      - export FRONTEND_URL="https://main.${AMPLIFY_APP_ID}.amplifyapp.com"
      - echo "API Gateway URL=$API_GATEWAY_URL"
      - echo "User Pool ID=$USER_POOL_ID"
      - echo "Region=$AWS_REGION"
      - echo ""
      - echo "=== FRONTEND DEPLOYMENT ==="
      - cd frontend
      - echo "Installing frontend dependencies..."
      - npm ci
      - echo "Setting environment variables for build..."
      - echo "NEXT_PUBLIC_API_BASE_URL=$API_GATEWAY_URL" > .env.local
      - echo "NEXT_PUBLIC_AWS_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=$USER_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_DOMAIN=$COGNITO_DOMAIN" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN=$FRONTEND_URL/auth/callback" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT=$FRONTEND_URL" >> .env.local
      - echo "Building Next.js application..."
      - npm run build 2>&1 | tee build.log
      - |
        # Check for build errors in output
        if grep -qi "error" build.log && ! grep -qi "0 error" build.log; then
          echo "[ERROR] Next.js build had errors"
          cat build.log
          exit 1
        fi
        # Validate Next.js build output
        if [ ! -d "out" ] || [ -z "$(ls -A out)" ]; then
          echo "[ERROR] Next.js build failed - no output directory or empty"
          exit 1
        fi
        echo "[SUCCESS] Next.js build completed successfully"
      - echo "Creating deployment package..."
      - cd out && zip -r build.zip .

  post_build:
    commands:
      - echo "Deploying frontend to Amplify..."
      - echo "Creating Amplify deployment..."
      - cd ../..
      - |
        # Create deployment and capture both exit code and output
        if aws amplify create-deployment --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION --output json > deployment_response.json 2>&1; then
          echo "[SUCCESS] Amplify deployment created successfully"
        else
          DEPLOYMENT_ERROR=$(cat deployment_response.json)
          # Check if error is because deployment already exists (not a real failure)
          if echo "$DEPLOYMENT_ERROR" | grep -q "already running\|already exists\|BadRequestException"; then
            echo "[WARNING] Deployment already in progress, checking status..."
            # Try to get the active job ID
            ACTIVE_JOB=$(aws amplify list-jobs --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION --query 'jobSummaries[?status==`PENDING` || status==`PROVISIONING` || status==`RUNNING`].jobId' --output text 2>/dev/null | head -1)
            if [ -n "$ACTIVE_JOB" ]; then
              echo "[SUCCESS] Found active deployment job: $ACTIVE_JOB"
              echo "Complete deployment finished successfully! (Using existing deployment)"
              exit 0
            fi
          fi
          echo "[ERROR] Failed to create Amplify deployment"
          cat deployment_response.json
          exit 1
        fi
      - echo "Extracting upload URL and job ID..."
      - |
        # Use jq for safer JSON parsing
        if command -v jq >/dev/null 2>&1; then
          export UPLOAD_URL=$(jq -r '.zipUploadUrl // empty' deployment_response.json)
          export JOB_ID=$(jq -r '.jobId // empty' deployment_response.json)
        else
          # Fallback to node if jq not available
          export UPLOAD_URL=$(node -e "const data=require('./deployment_response.json'); console.log(data.zipUploadUrl)")
          export JOB_ID=$(node -e "const data=require('./deployment_response.json'); console.log(data.jobId)")
        fi
        if [ -z "$UPLOAD_URL" ] || [ -z "$JOB_ID" ]; then
          echo "[ERROR] Failed to extract deployment URLs from response"
          cat deployment_response.json
          exit 1
        fi
      - echo "Uploading build.zip to Amplify..."
      - cd frontend/out
      - |
        # Upload with better error handling
        if curl -X PUT -T build.zip "$UPLOAD_URL" -f -s -S > /dev/null 2>&1; then
          echo "[SUCCESS] Build.zip uploaded successfully"
        else
          echo "[ERROR] Failed to upload build.zip to Amplify"
          exit 1
        fi
      - echo "Starting deployment..."
      - aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION || echo "[WARNING] Deployment start command completed (may already be running)"
      - echo "Complete deployment finished successfully!"

