version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Installing zip utility for frontend..."
      - yum install -y zip

  pre_build:
    commands:
      - echo "=== BACKEND DEPLOYMENT ==="
      - echo "Changing into backend directory"
      - cd backend
      - echo "Installing backend dependencies..."
      - npm ci
      - echo "Building TypeScript..."
      - npm run build
      - echo "Bootstrapping CDK..."
      - cdk bootstrap --require-approval never --context amplifyAppId=$AMPLIFY_APP_ID

  build:
    commands:
      - echo "Deploying CDK stack..."
      - cdk deploy --require-approval never --context amplifyAppId=$AMPLIFY_APP_ID
      - echo "CDK deployment complete."
      - echo "Extracting API Gateway URL and Cognito configuration..."
      - cd ..
      - export API_GATEWAY_URL=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export IDENTITY_POOL_ID=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export COGNITO_DOMAIN=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`CognitoDomain`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      - export AWS_REGION=$(aws cloudformation describe-stacks --stack-name AdaClaraUnifiedStack --query 'Stacks[0].Outputs[?OutputKey==`Region`].OutputValue' --output text --region $AWS_DEFAULT_REGION)
      # AMPLIFY_APP_ID is passed from deploy.sh as environment variable (created before CDK deployment)
      - export FRONTEND_URL="https://main.${AMPLIFY_APP_ID}.amplifyapp.com"
      - echo "API Gateway URL=$API_GATEWAY_URL"
      - echo "User Pool ID=$USER_POOL_ID"
      - echo "Region=$AWS_REGION"
      - echo ""
      - echo "=== FRONTEND DEPLOYMENT ==="
      - cd frontend
      - echo "Installing frontend dependencies..."
      - npm ci
      - echo "Setting environment variables for build..."
      - echo "NEXT_PUBLIC_API_BASE_URL=$API_GATEWAY_URL" > .env.local
      - echo "NEXT_PUBLIC_AWS_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REGION=$AWS_REGION" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=$USER_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_DOMAIN=$COGNITO_DOMAIN" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN=$FRONTEND_URL/auth/callback" >> .env.local
      - echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT=$FRONTEND_URL" >> .env.local
      - echo "Building Next.js application..."
      - npm run build
      - echo "Creating deployment package..."
      - cd out && zip -r build.zip .

  post_build:
    commands:
      - echo "Deploying frontend to Amplify..."
      - echo "Creating Amplify deployment..."
      - cd ../..
      - aws amplify create-deployment --app-id $AMPLIFY_APP_ID --branch-name main --region $AWS_DEFAULT_REGION --output json > deployment_response.json
      - |
        if [ $? -ne 0 ]; then
          echo "Failed to create Amplify deployment. Check if a deployment is already running."
          cat deployment_response.json
          exit 1
        fi
      - echo "Extracting upload URL and job ID..."
      - export UPLOAD_URL=$(node -e "const data=require('./deployment_response.json'); console.log(data.zipUploadUrl)")
      - export JOB_ID=$(node -e "const data=require('./deployment_response.json'); console.log(data.jobId)")
      - echo "Uploading build.zip to Amplify..."
      - cd frontend/out
      - curl -X PUT -T build.zip "$UPLOAD_URL"
      - |
        if [ $? -ne 0 ]; then
          echo "Failed to upload build.zip to Amplify"
          exit 1
        fi
      - echo "Starting deployment..."
      - aws amplify start-deployment --app-id $AMPLIFY_APP_ID --branch-name main --job-id $JOB_ID --region $AWS_DEFAULT_REGION
      - echo "Complete deployment finished successfully!"

